server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml       # mapper映射文件

spring:
   application:
    name: mybatis-select
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.200:3306/mybatisdb01?useUnicode=true&amp;characterEncoding=UTF-8                # 数据库名称
    username: mysql
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
logging:
  level:
     com.study.service: debug